language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
before_install:
    # Travis has got a default config, that we override for our tests.
    # See: https://github.com/travis-ci/travis-ci/issues/7940
    - sudo rm -f /etc/boto.cfg
install:
    - pip install tox
script:
    - tox -e $TOX_ENV

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.6
      env:
        - TOX_ENV=flake8
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37
