on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Unit Testing
jobs:
  chore:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [py37, py38, py39, py310, py311, flake8]
        include:
          - toxenv: py37
            python-version: "3.7"
          - toxenv: py38
            python-version: "3.8"
          - toxenv: flake8
            python-version: "3.8"
          - toxenv: py39
            python-version: "3.9"
          - toxenv: py310
            python-version: "3.10"
          - toxenv: py311
            python-version: "3.11"

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the latest commit, only
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install virtualenv
        run: |
          pip install virtualenv
          virtualenv --python=python3 .venv
      - name: Print environment
        run: |
          source .venv/bin/activate
          python --version
          pip --version
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install tox
      - name: Cleanup boto
        run: |
          rm -fr /etc/boto.cfg
      - name: Tox
        run: |
          source .venv/bin/activate
          tox -e ${{ matrix.toxenv }}
